Virtualize-dashboard-tiles
PrefectHQ/ui pull request #1120
Opened 2021-11-09 15:56 UTC by stackoverfloweth

PR Checklist:

- [ ] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR

2021-11-10 22:38 UTC, pleek91 reviewed
LGTM

2021-11-10 22:38 UTC, pleek91 commented on src/utils/dateTime.js
> +export function durationDifference(start, end) {
this is a cool utility method. nice job

2021-11-11 16:44 UTC, stackoverfloweth commented on src/utils/dateTime.js
> +export function durationDifference(start, end) {
gracias 🙏

2021-11-11 21:27 UTC, zangell44 commented on src/components/DurationSpan.vue
> +      >{{ duration.days }} {{ plural('day', duration.days.length) }}</span
I think we need to check if `duration` is null for this span, I'm seeing errors locally 

```
Vue Global Error Handler {error: TypeError: Cannot read properties of null (reading 'days')
```

2021-11-11 22:02 UTC, zhen0 submitted a review, later dismissed
This is looking nice @stackoverfloweth - I can see a reduction in errors in the dev console on this branch. 

One requested change for duration:

If the duration is less than a certain unit (e.g. day) can we exclude that unit (as we currently do in staging):

This branch:

<img width="1021" alt="Screen Shot 2021-11-11 at 4 06 54 PM" src="https://user-images.githubusercontent.com/40272060/141369360-720086e4-d384-4cb6-851c-d8292b0d58fa.png">

Desired/current staging:
<img width="1004" alt="Screen Shot 2021-11-11 at 4 07 02 PM" src="https://user-images.githubusercontent.com/40272060/141369382-da108d04-f1c1-459f-96c9-fd8673a5dc51.png">

And with the latest change there's possibly also a spacing/formatting issue (space before the comma):
<img width="695" alt="Screen Shot 2021-11-11 at 5 00 55 PM" src="https://user-images.githubusercontent.com/40272060/141375227-937be067-f5e6-418c-946d-da531b2cf246.png">

2021-11-13 16:35 UTC, zhen0 submitted a review, later dismissed
Still going through this one but wanted to note that i'm seeing an issue with running flows not showing in the runs in progress tile:

<img width="533" alt="Screen Shot 2021-11-13 at 11 33 50 AM" src="https://user-images.githubusercontent.com/40272060/141651540-04b5c61a-d95c-42f2-9916-f443e6d0c756.png">

2021-11-18 23:07 UTC, zhen0 submitted a review, later dismissed
When flow runs are in a cancelling state I see the following error message in the console: 
```
"Invalid prop: type check failed for prop \"endTime\". Expected String with value \"Thu Nov 18 2021 17:57:37 GMT-0500 (Eastern Standard Time)\", got Date "
```

This also seems to **very briefly** take up a lot of CPU:

<img width="547" alt="Screen Shot 2021-11-18 at 5 57 46 PM" src="https://user-images.githubusercontent.com/40272060/142510688-dfe42dc2-0ea3-4b84-8d1f-26bd1c7b756f.png">

Otherwise, I can now see all running and submitted states and I've not experienced any page freezes even when running late runs etc.

2021-11-29 22:01 UTC, stackoverfloweth commented
> When flow runs are in a cancelling state I see the following error message in the console:
> 
> ```
> "Invalid prop: type check failed for prop \"endTime\". Expected String with value \"Thu Nov 18 2021 17:57:37 GMT-0500 (Eastern Standard Time)\", got Date "
> ```
> 
> This also seems to **very briefly** take up a lot of CPU:
> 
> <img alt="Screen Shot 2021-11-18 at 5 57 46 PM" width="547" src="https://user-images.githubusercontent.com/40272060/142510688-dfe42dc2-0ea3-4b84-8d1f-26bd1c7b756f.png">
> 
> Otherwise, I can now see all running and submitted states and I've not experienced any page freezes even when running late runs etc.

I think this error did exist before me, the date coming down from the graphql query has a native date for some reason, and the component expects either null or string.
<img width="533" alt="Screen Shot 2021-11-29 at 3 54 54 PM" src="https://user-images.githubusercontent.com/6098901/143949693-6db7c76a-761f-4ca1-82fb-8fdfd06c49e3.png">

I think the reason we’re not seeing it on dev is maybe because it’s running “production” code via npm run build? I believe that would remove these vue global warnings

I checked out master and confirmed that I get those same warnings on “cancelling” flows

2021-11-30 14:45 UTC, stackoverfloweth commented
note from discussion around native `end_time`. I verified that the data coming back from apollo goes from state "scheduled" 
```
{
    "id": "e66d3237-66b0-4065-adf6-0f7d41bc05d2",
    "name": "beryl-raccoon",
    "state": "Scheduled",
    "labels": [
        "Evans-MacBook-Pro-2.local"
    ],
    "scheduled_start_time": "2021-11-30T10:01:33.24699+00:00",
    "version": 1,
    "flow": {
        "id": "7b881aa0-5b0e-49e9-a4d9-f074960f901f",
        "name": "slow-flow",
        "schedule": null,
        "environment": null,
        "is_schedule_active": true
    }
}
```

to state "cancelling", always with a normal looking `start_time` and no `end_time`
```
{
    "id": "742dd5ce-25d6-4c0a-9a1a-7dba31dbf7e1",
    "name": "cinnamon-raccoon",
    "start_time": "2021-11-30T14:39:53.986704+00:00",
    "state": "Cancelling",
    "state_timestamp": "2021-11-30T14:41:41.458238+00:00",
    "flow": {
        "id": "7b881aa0-5b0e-49e9-a4d9-f074960f901f",
        "name": "slow-flow",
        "flow_group_id": "b6856226-145d-4955-a066-e022adb88f04"
    },
    "updated": "2021-11-30T14:41:41.527171+00:00"
}
```

2021-11-30 15:00 UTC, stackoverfloweth commented
I found it, this component `Dashboard/FlowRunHistory-Tile.vue` has the apollo query for the data above, passes the items down to `components/TimelineTooltip.vue`, which is ultimately where DurationSpan is throwing these warnings for receiving a native `endTime` instead of null | string. The items passed come from the FlowRunHistory-Tile's mixin `flowRunHistoryMixin.js`, which is setting `end_time` to a new Date() on line 119.

<img width="481" alt="Screen Shot 2021-11-30 at 8 59 32 AM" src="https://user-images.githubusercontent.com/6098901/144071274-401299e9-dbc5-4727-a07c-400c132c722b.png">
.

2021-11-30 20:17 UTC, pleek91 commented on src/components/DurationSpan.vue
> +} from '@/utils/dateTime'
nit: two import statements from the same file.

2021-11-30 20:17 UTC, pleek91 commented on src/components/DurationSpan.vue
> +</style>
What does this css do? There's not class `duration-span__block` in the template.

2021-11-30 21:35 UTC, zhen0 commented
Thanks for tracking that down @stackoverfloweth - this LGTM and happy to approve once Craig's comments are addressed.

2021-12-01 15:10 UTC, zhen0 requested changes
Thanks for tracking that down @stackoverfloweth - this LGTM and happy to approve once Craig's comments are addressed.

2021-12-01 21:24 UTC, zhen0 approved these changes
Thanks for the changes @stackoverfloweth

2021-12-01 21:24 UTC, merged