auto changelog
PrefectHQ/ui pull request #1171
Opened 2021-12-14 22:58 UTC by stackoverfloweth

- auto-changelog setup
- new changelog generated

PR Checklist:

- [ ] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR

2021-12-16 22:31 UTC, zhen0 commented
I'm onboard with adding auto-changelog as a dependency. I also like the simplicity of being able to run `npm run changelog` to create the changelog for a release without needing to append or delete entries.  This could be a useful pattern for other repos too.  Is it something we could potentially automate also?

2021-12-20 20:10 UTC, zhen0 commented
While looking for something else, I just realized github has an option to automatically create release notes.  This would simplify our release process even more than auto-changelog and is configurable. I'd welcome thoughts on this as an option.

2021-12-21 14:59 UTC, stackoverfloweth commented
@zhen0 I looked into github generated release notes, it looks like a great option! (example below)

The only caveat I see is that we would no longer have a physical file in our repository, release notes would only be available on github. I personally think this is fine but we should validate that nobody objects to deleting of changelog.md from our repository.

## What's Changed
* Cut Changelog ahead of 2021-12-15 release by @stackoverfloweth in https://github.com/PrefectHQ/ui/pull/1175
* BugFix: Replacing link to docs in task run concurrency page by @kvnkho in https://github.com/PrefectHQ/ui/pull/1176
* added http-security-headers to apollo graphql network traffic by @stackoverfloweth in https://github.com/PrefectHQ/ui/pull/1173
* BugFix: removed unused onIntersect methods by @stackoverfloweth in https://github.com/PrefectHQ/ui/pull/1166

## New Contributors
* @kvnkho made their first contribution in https://github.com/PrefectHQ/ui/pull/1176

**Full Changelog**: https://github.com/PrefectHQ/ui/compare/2021-12-15...2021-12-21

2021-12-23 03:10 UTC, zhen0 commented
Good question @stackoverfloweth - I've shared this question in slack to see if we can gain consensus.  For this repo I'm not convinced about the benefit of completely replacing the changelog since the entries in there took time and effort to represent the work that had been done.  Cutting a changelog also gives me a chance to check the QA checklist has been completed.

2021-12-23 04:03 UTC, zhen0 commented
So my vote would be to add the npm script but not completely overwrite the existing changelog.

2021-12-23 04:05 UTC, zhen0 requested changes
Happy to approve this if we remove the changelog override.

2021-12-23 14:13 UTC, zhen0 approved these changes
@stackoverfloweth - I'm happy to give this a trial.  We can always revert if we find we want that more detailed log.  The more thought through changelog descriptions will be maintained in the release notes and the changelog.md file contains PR links that let us see what was released when.  Your change here also makes it easier to run auto-changelog to see what is still unreleased.  

I think you'll need to fix the merge conflict on changelog.md though.

2021-12-23 22:11 UTC, zhen0 approved these changes

2021-12-24 16:15 UTC, merged