Feature: Adds Salesforce Chat Bot
PrefectHQ/ui pull request #1250
Opened 2022-03-09 17:25 UTC by space-age-pete

## Description
Adds the Salesforce Chat Bot, which provides either live chat, or recommends articles, based on the user's Salesforce Account ID, which is included in the "terms" field in the License table. This code comes from a modified code snippet provided by Salesforce. The Content-Security-Policy meta tag in the index.html file is updated to allow this embed, and some css is also added to the same file.

## Tests and performance

 - [X] Changes to any .js files are covered by existing tests or this PR adds new tests (if not please explain why below)
 - no changes to .js files
 - [X] No new packages are added or package size and performance considerations are discussed below
 - [X] PR Title fits our [changelog format](https://github.com/PrefectHQ/ui#readme)

2022-03-09 19:47 UTC, znicholasbrown requested changes

2022-03-09 19:47 UTC, znicholasbrown commented on src/App.vue
> +
This is the wrong location for this logic - it should most likely be in its own file in the `plugins` directory and initialized in `main.js` after checking that we're in a cloud environment (the node_env shouldn't matter)

2022-03-09 19:47 UTC, znicholasbrown commented on src/App.vue
> +    var initESW = function(gslbBaseURL) {
```suggestion
    const initESW = function(gslbBaseURL) {
```

2022-03-09 19:47 UTC, znicholasbrown commented on src/App.vue
> +      var s = document.createElement('script')
```suggestion
      const s = document.createElement('script')
```

2022-03-09 19:47 UTC, znicholasbrown commented on src/App.vue
> +              'https://d.la1-c2-ia2.salesforceliveagent.com/chat'
Maybe these should pull from environment variables and only live in CICD?

2022-03-09 19:47 UTC, znicholasbrown commented on public/index.html
> +      frame-src 'self' * data: https://*.prefect.io https://prefect.auth0.com https://js.stripe.com https://cloud.prefect.io https://*.okta.com;
Is a wildcard correct here?

2022-03-14 18:21 UTC, jawnsy commented on .circleci/config.yml
> +              export $line
GitHub has a magic file you can write to, in order to set env vars (`$GITHUB_ENV`), so you might be able to just cat into that instead: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable

2022-03-14 18:21 UTC, jawnsy commented on .circleci/config.yml
> +              export $line
ah nevermind, this is for Circle CI

2022-03-24 21:20 UTC, znicholasbrown approved these changes

2022-03-24 21:21 UTC, merged