Unit tests store tenant
PrefectHQ/ui pull request #195
Opened 2020-09-03 18:14 UTC by zhen0

PR Checklist:

- [ ] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR

2020-09-11 17:43 UTC, znicholasbrown requested changes
Overall looks good @zhen0 - I've added some comments and suggestions.

2020-09-11 17:43 UTC, znicholasbrown commented on tests/unit/store/tenant.spec.js
> +      it('should set tenants', async () => {
```suggestion
      it('should call the prefectTenants method', async () => {
```

2020-09-11 17:43 UTC, znicholasbrown commented on tests/unit/store/tenant.spec.js
> +    describe('setCurrentTenant -server', () => {
```suggestion
    describe('setCurrentTenant - Server', () => {
```

2020-09-11 17:43 UTC, znicholasbrown commented on tests/unit/store/tenant.spec.js
> +    describe('setCurrentTenant - Cloud specific', () => {
```suggestion
    describe('setCurrentTenant - Cloud', () => {
```

2020-09-11 17:43 UTC, znicholasbrown commented on tests/unit/store/tenant.spec.js
> +      it('should check if tenant is set and getTenant if not set', async () => {
```suggestion
      it('should call getTenants if the passed tenant is not present in the store', async () => {
```

2020-09-11 17:43 UTC, znicholasbrown commented on tests/unit/store/tenant.spec.js
> +        expect(store.getters.tenant.slug).toEqual('team2')
Let's test this against the entire tenant object described in `tenantsArray`

2020-09-11 17:43 UTC, znicholasbrown commented on tests/unit/store/tenant.spec.js
> +      it('should set the tenant role to Tenant Admin', async () => {
```suggestion
      it('should set the tenant role to TENANT_ADMIN', async () => {
```

2020-09-11 17:43 UTC, znicholasbrown commented on tests/unit/store/tenant.spec.js
> +      it('should set the tenant role to Tenant Admin', async () => {
Can you add a comment describing why this is the case? It'll be useful when debugging this for someone unfamiliar with the differences between Server and Cloud.

2020-09-11 17:43 UTC, znicholasbrown commented on tests/unit/store/tenant.spec.js
> +      it('should set the tenant role according to user memberships', async () => {
Maybe this should be a sub-describe block that tests each of the 3 roles?

2020-09-11 17:43 UTC, znicholasbrown commented on tests/unit/store/tenant.spec.js
> +
Seems like we could add another test here for the update tenant settings mutation:
```
it ('should call the UpdateTenantSettings mutation with the passed settings', async () => {
  expect(mockedUpdateTenantSettings).toHaveBeenCalledWith({ variables: { name: 'Jerry' } })
})
```

2020-09-16 13:52 UTC, zhen0 commented
Thanks for the comments @znicholasbrown - ready for another review

2020-09-16 17:27 UTC, znicholasbrown approved these changes
Thanks for the changes @zhen0 !

2020-09-16 17:28 UTC, merged