Apollo endpoint usability update
PrefectHQ/ui pull request #241
Opened 2020-09-21 18:25 UTC by znicholasbrown

PR Checklist:

- [ ] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR
* Removes `BASE_URL` from the environment variables file
* Fetch `prefect_ui_settings` static JSON from `/` instead of the base url
* Add a reset method to the GraphQL endpoint setter input, which will clear the `localStorage` `server_url` key and reset default URL to whatever was configured either from the environment or the settings.json

Should make deploying to a remote server with a non-static domain easier

2020-09-22 19:16 UTC, zhen0 requested changes
I like the addition of the rest but one suggestion/request @znicholasbrown

2020-09-22 19:16 UTC, zhen0 commented on src/pages/Home/StartPrefectServer-Section.vue
> +                  <v-fade-transition mode="out-in">
I find the mix of indicator and action button a bit confusing here.  Could we keep the indicator as is and add a reset button next to the connect button?  (Or something similar.)

2020-09-23 15:24 UTC, znicholasbrown commented
Good call @zhen0 - that's been updated:
![Screen Shot 2020-09-23 at 11 24 23 AM](https://user-images.githubusercontent.com/27291717/94033836-59fb1800-fd8f-11ea-8c82-20e3748582be.png)

2020-09-23 15:33 UTC, zhen0 approved these changes
Thanks for the changes @znicholasbrown

2020-09-23 15:42 UTC, merged