update url regex
PrefectHQ/ui pull request #277
Opened 2020-09-30 22:12 UTC by zhen0

PR Checklist:

- [ ] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR

2020-10-01 15:11 UTC, znicholasbrown requested changes

2020-10-01 15:11 UTC, znicholasbrown commented on src/components/CloudHookForm.vue
> +          const pattern = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)/
The `/https?\/\/` section means a protocol would be required for a Cloud Hook, which is a departure from previous functionality. I might replace that with an optional capture group instead.

2020-10-01 15:56 UTC, zhen0 commented
Good point @znicholasbrown - I've updated the regex to allow urls without http protocol

2020-10-05 22:03 UTC, znicholasbrown approved these changes
LGTM @zhen0 👍

2020-10-05 22:04 UTC, merged