fetch task runs for mark as dialog
PrefectHQ/ui pull request #411
Opened 2020-11-09 22:26 UTC by zhen0

PR Checklist:

- [ ] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR

2020-11-09 23:00 UTC, znicholasbrown requested changes
This will most likely fail for large mapped pipelines - I'm not sure how we want to address that UX. Maybe we should filter out task runs with `> -1` map index? Other than that, just one issue to fix.

2020-11-10 22:54 UTC, zhen0 commented
Actually - not ready for review - just seen something else that needs updating...

2020-11-11 17:57 UTC, znicholasbrown requested changes
This is working great @zhen0, just 1 suggestion to clean up the task run ids query file.

2020-11-11 17:57 UTC, znicholasbrown commented on src/graphql/FlowRun/task-run-ids.gql
> +}
```suggestion
query taskRunIds($flowRunId: uuid!, $parentMapIndex: Int, $childMapIndex: Int) {
  task_run(
    where: {
      _and: [
        { flow_run_id: { _eq: $flowRunId } }
        { map_index: { _eq: $parentMapIndex } }
        { map_index: { _gte: $childMapIndex } }
      ]
    }
  ) {
    version
    id
    map_index
  }
}

```
Just to clean this file up a bit

2020-11-11 18:03 UTC, zhen0 commented
Thanks @znicholasbrown - made that clean up.  (This whole feature needs a re-factor at some point!)

2020-11-11 20:22 UTC, znicholasbrown approved these changes

2020-11-11 20:22 UTC, merged