Flow run artifacts
PrefectHQ/ui pull request #484
Opened 2020-12-02 19:39 UTC by znicholasbrown

PR Checklist:

- [ ] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR
Exposes the artifacts API.

TODO:
* [ ] fetch all (some?) task run artifacts on the flow run page
* [x] fetch all task run artifacts and display on the task run page
* [x] artifact markdown styling
* [ ] list results in a user-friendly way with lazy loading (probably should use a wrapper component for this)

2020-12-05 01:07 UTC, znicholasbrown commented
This is ready for review.

Things we'll introduce in the next iteration:
- pagination; for large mapped pipelines, the current implementation could potentially crash the browser tab
- directly linking to specific artifacts
- task and flow level artifacts (both require pagination)
- better grouping based on task (a task can have multiple artifacts and multiple task runs can produce artifacts... this is mostly for flow and flow run pages)
- searching for artifacts by task/task run name


cc @cicdw

2020-12-05 01:28 UTC, cicdw requested changes
Really minor word change suggestion, but I think this looks great!

2020-12-05 01:28 UTC, cicdw commented on src/pages/FlowRun/FlowRun.vue
> +            'The Artifacts API is a beta feature set currently under development. Task mapping with artifacts may have unexpected results... for more information on artifacts, check out the',
```suggestion
            'The Artifacts API is a beta feature currently under development. Task mapping with artifacts may have unexpected results... for more information on artifacts, check out the',
```

2020-12-07 16:44 UTC, znicholasbrown commented
Committed that suggestion @cicdw and fixed a couple of minor usability issues / bugs. Ready for review again @cicdw / @zhen0. We're also showing a friendlier message when no artifacts are present (and hid the navigation buttons).

2020-12-07 18:25 UTC, zhen0 approved these changes
Thanks for the changes @znicholasbrown LGTM!

2020-12-07 18:25 UTC, merged