check if flow version is archived for restart button state
PrefectHQ/ui pull request #714
Opened 2021-03-31 15:29 UTC by whimsicallyson

PR Checklist:

- [ ] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR
Fixes #446, only allows you to click the restart button on a flow run if it isn't an archived version.

2021-03-31 21:24 UTC, znicholasbrown requested changes
I don't think we need to add a new query for the flow in this component, since the flow object is being passed with the `flowRun` prop; adding the `archived` field there is better in this case.

2021-03-31 21:35 UTC, whimsicallyson commented
ugh I can't believe I missed that!

2021-03-31 21:53 UTC, znicholasbrown commented on src/graphql/Flow/flow-by-pk.gql
> +}
Can we remove this change as well?

2021-04-07 16:14 UTC, znicholasbrown approved these changes
LGTM 👍

2021-04-07 16:14 UTC, merged