Add recently updated flow tile
PrefectHQ/ui pull request #822
Opened 2021-05-08 16:07 UTC by zangell44

PR Checklist:

- [ ] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR

2021-05-08 16:15 UTC, zangell44 commented on src/pages/Dashboard/FlowRecentUpdate.vue
> +        ]
do I need to explicitly add `tenant` to the search params here?

2021-05-10 14:01 UTC, znicholasbrown commented
Previews should be working for this 👍

2021-05-10 15:15 UTC, znicholasbrown requested changes
Hm I don't think this is quite the correct way to do this.

1) This shouldn't be a dashboard tile; those should be reserved for static content
2) This isn't dismissible by the user, even after clicking "Go to flow"
3) This requires a quite aggressive query to display; I wonder if the global flows query might be used instead? This way we could watch the store and not poll on this component at all

Some suggestions:
Add the `updated` field to the global flows query (`@/graphql/Nav/flows.gql`); watch the store for changes to that
Use [Vuetify snackbars](https://vuetifyjs.com/en/components/snackbars/) for display; by default these are dismissible and survive route changes; we can make use of either local storage or the user settings blob to keep track of which flows (and versions) have been acked by the user 
Use existing date time methods for date formatting; we've got a bunch of useful methods in `@/mixins/formatTime.js` 😄

2021-11-09 20:17 UTC, zhen0 commented
@zangell44 - can we close this for now?

2021-11-11 22:33 UTC, zhen0 commented
Discussed with @zangell44 and closing for now as this is no longer a priority

2021-11-11 22:33 UTC, closed without merging