Add agents
PrefectHQ/ui pull request #852
Opened 2021-05-19 21:37 UTC by zhen0

PR Checklist:

- [ ] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR

2021-05-27 18:06 UTC, znicholasbrown commented
Some initial comments:
- Cleaning up agents doesn't seem to be working as intended; the first time I press the button nothing seems to have happened and the second time only greyed-out agents were cleaned up. It doesn't seem like unhealthy agents are all removed, maybe because they have submittable or late runs?
- This dialog box is really big:
![Screen Shot 2021-05-27 at 1 47 53 PM](https://user-images.githubusercontent.com/27291717/119873394-7e952a00-bef2-11eb-8c99-c85553803114.png)
- When filters are applied, the toast message blocks content:
![Screen Shot 2021-05-27 at 1 50 58 PM](https://user-images.githubusercontent.com/27291717/119873462-92409080-bef2-11eb-9ef6-aa2ccb8e4a94.png)
- Is the "Recent Runs" bullet point pointing to the chart below? If so, that isn't super clear since it's in the same format as the single-line information above (submittable runs and last queried)
![Screen Shot 2021-05-27 at 1 51 37 PM](https://user-images.githubusercontent.com/27291717/119873671-c4ea8900-bef2-11eb-80d5-bf559dfa9aa2.png)
- Query times don't seem to be counting up and the tooltip timestamp is incorrect (I think; this screenshot was taken at 13:41 EST):
![Screen Shot 2021-05-27 at 1 41 16 PM](https://user-images.githubusercontent.com/27291717/119873796-e77ca200-bef2-11eb-9c08-de6eed111233.png)

On the agent page:
- This is overall looking nice! The numbers in this screenshot correspond to the numbered feedback:
![Screen Shot 2021-05-27 at 1 54 21 PM](https://user-images.githubusercontent.com/27291717/119874668-dda76e80-bef3-11eb-9dcd-e9a28454f4f6.png)
1. We should use the agent name or a more human-friendly default for unnamed agents instead of the id
2. This is a really large amount of padding - it should probably match the padding on the flow run page
3. The typography here makes it difficult to parse key:value; a design similar to the overview tile on flow run pages would help a lot (floated key:values with differing font weights)
4. (this applies to the agent overview cards on `/agents`): when there are no labels, we should display something to that effect, instead of having nothing at all. Maybe "No labels" with `text--disabled` applied?
5. Duplicate wording on this tile; since it's on the agent page, it can be inferred that the config is an agent config. I'm also thinking this tile feels a little unimportant. Maybe using a similar top-right tab style to the flow page details would be better? Then we can trim the wording a lot, with just a `Config` tab and `No config` when there isn't one.
![Screen Shot 2021-05-27 at 2 04 47 PM](https://user-images.githubusercontent.com/27291717/119875253-8ce44580-bef4-11eb-9a49-a55281423054.png)


Small note: the styling for upcoming runs (on which the submittable runs tile is based) has changed a bit for clarity, so this design should be updated as well.

2021-06-07 16:11 UTC, zhen0 commented
@znicholasbrown - This one is waiting for review.

2021-06-08 01:56 UTC, znicholasbrown requested changes
A few pieces of feedback that weren't addressed from the last review:
- [x] the padding between tiles is uneven
- [ ] The typography on the overview tile makes it difficult to parse key:value; a design similar to the overview tile on flow run pages would help a lot (floated key:values with differing font weights)
- [x] when no config is present we can say "No config" instead of "no agent config is present on this agent", which feels redundant


And some new feedback:
- [x] the first row agent page tiles are too tall; on a medium dpi laptop they have a lot of unused whitespace and hide the next row below the fold:
<img width="512" alt="Screen Shot 2021-06-07 at 9 31 58 PM" src="https://user-images.githubusercontent.com/27291717/121109248-31119a80-c7d9-11eb-839d-ee112823c0da.png">


- [x] I think this would feel better if you used `/agent` as the root page and then added breadcrumbs on the individual agent pages to get back to the primary agents screen (so `/agent/:id?` for the route, showing all the agents tiles when no id is provided)
<img width="634" alt="Screen Shot 2021-06-07 at 9 32 46 PM" src="https://user-images.githubusercontent.com/27291717/121109444-96fe2200-c7d9-11eb-9137-13f16543f0b1.png">

- [x] the agent timeline is missing flow names
<img width="634" alt="Screen Shot 2021-06-07 at 9 36 00 PM" src="https://user-images.githubusercontent.com/27291717/121109611-ed6b6080-c7d9-11eb-84e0-d2696d4f766c.png">

- [x] the space between recent runs and last queried could use a visual break - maybe a horizontal rule would help here?
<img width="362" alt="Screen Shot 2021-06-07 at 9 40 50 PM" src="https://user-images.githubusercontent.com/27291717/121109653-fbb97c80-c7d9-11eb-82c4-6a73f5f6d266.png">

- [x] agents with no recent runs just show a line; it'd be good to have some text letting the user know there are no runs like on the flow/dashboard pages' timelines
<img width="362" alt="Screen Shot 2021-06-07 at 9 48 29 PM" src="https://user-images.githubusercontent.com/27291717/121109787-36231980-c7da-11eb-9191-9f0458f1c00e.png">

- [x] instead of 720 minutes, let's put 12 hours here
<img width="362" alt="Screen Shot 2021-06-07 at 9 56 52 PM" src="https://user-images.githubusercontent.com/27291717/121110477-5901fd80-c7db-11eb-8bcd-67d65311ce2e.png">

2021-06-10 02:33 UTC, znicholasbrown commented
Another note: I think this can be improved a bit; we probably don't need to hide the subpage nav bar when there are no agents since this looks like a UI error and not something actionable for the user. I'd also change the wording a little:
> You have no agents querying for runs.
> For help setting up an agent, check out the agent [docs] or [tutorial].

![Screen Shot 2021-06-09 at 10 28 22 PM](https://user-images.githubusercontent.com/27291717/121455515-99e04a80-c972-11eb-9c27-198d9847a29c.png)

2021-06-11 14:20 UTC, zhen0 commented
Made those changes @znicholasbrown - ready for review.

2021-06-14 17:38 UTC, znicholasbrown requested changes
Some small comments but mostly looks good 😄

2021-06-14 17:38 UTC, znicholasbrown commented on src/App.vue
> +    },
I'm a little confused what this watcher is doing that `this.$globalApolloQueries['agents'].refetch()` wouldn't do without a new store pattern

2021-06-14 17:38 UTC, znicholasbrown commented on src/graphql/Agent/FlowRuns.gql
> +  }
Since we have all flows in the data store, this query would be a lot more performant by grabbing the `flow_id` and tying the data together instead

2021-06-14 17:38 UTC, znicholasbrown commented on src/pages/Agents/AgentRunsInProgress.vue
> +<script>
It looks like this component isn't used, can it be removed?

2021-06-14 17:38 UTC, znicholasbrown commented on src/router.js
> +      import(/*webpackChunkName: "calendar" */ '@/pages/Agents/Agents')
```suggestion
      import(/*webpackChunkName: "agents" */ '@/pages/Agents/Agents')
```

2021-06-14 17:38 UTC, znicholasbrown commented on src/router.js
> +      import(/* webpackChunkName: "flow" */ '@/pages/Agents/AgentPage.vue')
```suggestion
      import(/* webpackChunkName: "agent" */ '@/pages/Agents/AgentPage.vue')
```

2021-06-15 15:28 UTC, znicholasbrown approved these changes
Thanks for the changes @zhen0 !

2021-06-15 15:28 UTC, merged