Improve type handling when passing parameters to create flow run mutation
PrefectHQ/ui pull request #936
Opened 2021-07-07 07:43 UTC by znicholasbrown

PR Checklist:

- [x] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR
Fixes an issue where the editor would incorrectly coerce single-item arrays to scalar values and non-strings to strings in JSON editing mode on the run page.

2021-07-07 08:42 UTC, zhen0 requested changes
One tiny nitpick from me but the type handling improvements look good.

2021-07-07 08:42 UTC, zhen0 commented on src/components/CustomInputs/DictInput.vue
> +        // console.log()
Could we take this out?

2021-07-07 18:12 UTC, znicholasbrown commented
@zangell44 - we haven't traditionally tested these components cause the tests ended up being very brittle but I agree this is something we should test in the future

2021-07-08 12:23 UTC, zhen0 approved these changes
Thanks for the change @znicholasbrown

2021-07-08 13:38 UTC, merged