Add run config tab to flow run page
PrefectHQ/ui pull request #942
Opened 2021-07-12 18:10 UTC by whimsicallyson

PR Checklist:

- [ ] add a short description of what's changed to the top of the `CHANGELOG.md`
- [ ] add/update tests (or don't, for reasons explained below)

## Describe this PR
If a run has custom config changes via the Run tab in the UI, these changes hadn't been shown once the run happens. This adds a tab to the flow run page so you can see what has been changed (or be told that nothing was changed)

2021-07-14 14:45 UTC, zhen0 requested changes
Thanks for this @whimsicallyson - this is looking nice.  One small request from me.

2021-07-14 14:45 UTC, zhen0 commented on src/pages/FlowRun/Run-Config-Tile.vue
> +                ><Label disabled>{{ label }}</Label></span
I think we need to add a tiny bit of padding between labels: 

<img width="765" alt="Screen Shot 2021-07-14 at 3 43 55 PM" src="https://user-images.githubusercontent.com/40272060/125641995-5209ef68-edb9-4076-ac0a-86450f483b62.png">

2021-07-18 10:41 UTC, zhen0 reviewed
Looks good to me.  Any thoughts @znicholasbrown?

2021-07-19 16:16 UTC, znicholasbrown requested changes
![Screen Shot 2021-07-19 at 11 58 06 AM](https://user-images.githubusercontent.com/27291717/126190834-db99807f-77aa-4ec8-93e6-441dece8bd7c.png)

Some things I noticed:
- for a default universal config, this screen is mostly whitespace; let's make the height for the container fit the contents
- the bottom few pixels of the container is cut off (notice the box shadow is missing)
- I don't think "Agent" is the correct label for the run config type, let's use "Run Configuration" as we do on the run page
- Lists of image pull secrets shouldn't show index numbers (see screenshot below)

There might be a better way to show plaintext values like these, where there isn't a confusion between keys and values and where templates use the syntax highlighting that we have:
![Screen Shot 2021-07-19 at 12 15 27 PM](https://user-images.githubusercontent.com/27291717/126192787-55628c77-a741-457c-8c6a-c3a3b0115632.png)

I'd also reinforce the feedback that values should be more pronounced than keys (like CPU Request, Memory Limit, etc)

2021-07-21 18:40 UTC, whimsicallyson commented
@znicholasbrown addressed everything except the yaml output, I haven't been able to find a way to reliably parse the plaintext string. Open to ideas!

2021-07-21 21:27 UTC, znicholasbrown commented
You should be able to use the `YamlInput` component to handle that, though with a `disabled` prop

2021-07-22 13:54 UTC, whimsicallyson commented
yaml and json are using the input components now! one final concern I can think of: for key/val pairs that can be input as KV or JSON, we have no way to differentiate how they were input, so are all being shown as JSON now (previously they were shown as plaintext KV pairs). I feel like this is ok though?

2021-08-06 19:48 UTC, zhen0 commented
Is this ready for review @whimsicallyson?

2021-08-06 19:49 UTC, whimsicallyson commented
@zhen0 not currently, there was some discussion with nicholas that wasn't captured here and I still need to finish implementing

2021-09-03 13:42 UTC, whimsicallyson commented
Closing this (at least for the time being), have some other things that have taken priority. Hope to get back to it soon though!

2021-09-03 13:42 UTC, closed without merging